### ISSUE TITLE
Problem with watch-server script on windows

### ISSUE THREAD

**Issue by BCool13** [EnterpriseJSTutorial/koa-typescript-starter#2]
Hello,

Thank you for this very informative example. Alas I believe that the script "watch-server" has a small error (at least under windows).

The current command line is:
```
cross-env NODE_ENV = development nodemon --watch 'src / ** / *' -e ts, tsx --exec 'ts-node' src / server / server.ts
```
But in this case ts-node is not called and causes an error.

If we use the modified command line:
```
cross-env NODE_ENV = development nodemon --watch 'src / ** / *' -e ts, tsx --exec ts-node src / server / server.ts
```
The error disappears.

**Comment by dupski** [comment]
Thanks @BCool13 , I have updated the `watch-server` script in package.json :)
